name: Android DEV Firebase Distribution

on:
  push:
    tags:
      - "dev-android-*"

jobs:
  android-dev:
    uses: ./.github/workflows/android/android-common.yml
    secrets: inherit
    working-directory: android
    with:
      fastlane_lane: dev
      environment: DEVELOPMENT
