name: Android DEV Firebase Distribution

on:
  push:
    tags:
      - "dev-*"

jobs:
  android-dev:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Java (Gradle needs JDK 17)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Setup Flutter (pakai channel beta untuk Dart >= 3.6.1)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "beta"

      # Setup Ruby & Bundler
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Decode Firebase DEV service account
        run: |
          echo "$FIREBASE_DEV_SERVICE_ACCOUNT" > firebase.json

        # Install Fastlane & plugins
      - name: Install Fastlane & plugins
        run: |
          cd android
          bundle install

      - name: Android DEV Distribute
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_DEV_APP_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: firebase.json
        run: fastlane dev
