name: Android PROD Release

on:
  push:
    tags:
      - "prod-android-*"

jobs:
  android-prod:
    uses: ./.github/workflows/android-common.yml
    secrets: inherit
    with:
      fastlane_lane: prod_release
      environment: PRODUCTION
