name: Flutter Test

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Setup Machine
        uses: ./.github/workflows/setup-common.yml

      - name: Run Flutter tests
        run: flutter test --coverage