name: iOS DEV Firebase Distribution

on:
  push:
    tags:
      - "dev-ios-*"

jobs:
  flutter-test:
    uses: ./.github/workflows/flutter-test.yml

  build:
    runs-on: macos-latest
    needs: flutter-test
    environment: "DEVELOPMENT"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/actions/setup-common

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod --version

      - name: Create Firebase service account file
        run: |
          mkdir -p credential
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > credential/firebase.json

      - name: Install iOS Pods
        run: |
          cd ${{ github.workspace }}/ios
          pod install --repo-update

      - name: IOS Build & Distribution
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credential/firebase.json
        run: |
          cd ios
          bundle install
          fastlane dev